plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.5'
}

ext {
    aeronVersion  = '1.48.0'
    agronaVersion = '2.2.1'
    vertxVersion  = '4.5.7'
}

dependencies {
    implementation project(':arb-common')
    implementation "io.aeron:aeron-client:${aeronVersion}"
    implementation "io.aeron:aeron-driver:${aeronVersion}"
    implementation "org.agrona:agrona:${agronaVersion}"
    implementation "io.vertx:vertx-core:${vertxVersion}"
    implementation "io.vertx:vertx-web:${vertxVersion}"
    implementation 'com.h2database:h2:2.2.224'

    testImplementation project(':arb-common')
    testImplementation "io.aeron:aeron-client:${aeronVersion}"
    testImplementation "org.agrona:agrona:${agronaVersion}"
    testImplementation "io.vertx:vertx-core:${vertxVersion}"
    testImplementation "io.vertx:vertx-web:${vertxVersion}"
}

jar {
    manifest {
        attributes 'Main-Class': 'com.arb.gateway.GatewayMain'
    }
}

shadowJar {
    archiveClassifier = 'all'
    mergeServiceFiles()
}
