plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.5'
}

ext {
    aeronVersion     = '1.48.0'
    agronaVersion    = '2.2.1'
    cucumberVersion  = '7.22.1'
}

dependencies {
    implementation project(':arb-common')
    implementation project(':arb-strategy')
    implementation "io.aeron:aeron-client:${aeronVersion}"
    implementation "org.agrona:agrona:${agronaVersion}"

    testImplementation project(':arb-common')
    testImplementation project(':arb-strategy')
    testImplementation "io.aeron:aeron-client:${aeronVersion}"
    testImplementation "io.aeron:aeron-driver:${aeronVersion}"
    testImplementation "org.agrona:agrona:${agronaVersion}"
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:${cucumberVersion}"
    testImplementation "org.junit.platform:junit-platform-suite:1.10.2"
}

jar {
    manifest {
        attributes 'Main-Class': 'com.arb.execution.ExecutionMain'
    }
}

shadowJar {
    archiveClassifier = 'all'
    mergeServiceFiles()
}
